### ISSUE TITLE
Handling of leftover RTEs

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#102]
The following test case

```
#include "unit-testing"

Function Dostuff()

	WAVE wv = $""
	print wv[0]

	print getrTError(1)
End
```

 gives

```
•runtest("procedure")
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Dostuff"
  NaN
  330
  The test case "Dostuff" did not make any assertions!
  Leaving test case "Dostuff"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

So we encountered an RTE but the testcase did not fail. Should we check that `getrTError(1)` returns 0 after each test case and fail otherwise?

**Comment by ukos-git** [comment]
This would be a good addition to check for a failure free program execution. This is good to check if the program executes normally without errors on certain input values but no output values are  generated or available. So the encountered Aborts are the failing condition.

Something like this can of course also get cached right now with a try-catch-endtry statement by the unit test itself, but I think, any encountered RTE is a failed unit test.

**Comment by t-b** [comment]
@ukos-git Same thinking here. Thanks for the input.

**Comment by t-b** [comment]
Clearing the RTE after a each test case also avoids the case where subsequent tests fail because of lingering RTEs.

**Comment by MichaelHuth** [comment]
```
/// @brief Helper function for try/catch with AbortOnRTE
///
/// Not clearing the RTE before calling `AbortOnRTE` will always trigger the RTE no
/// matter what you do in that line.
///
/// Usage:
/// \rst
/// .. code-block:: igorpro
///
///    try
///       ClearRTError()
///       myFunc(); AbortOnRTE
///    catch
///      err = GetRTError(1)
///    endtry
///
/// \endrst
threadsafe Function ClearRTError()

	variable err = GetRTError(1)
End

```

**Comment by t-b** [comment]
@MichaelHuth @MathiasAugstein A new improved version is available at https://github.com/AllenInstitute/MIES/pull/540/commits/012481b1783e29e3ed9f3a403c8441e6f92cc4d5.

**Comment by MathiasAugstein** [comment]
This function is already implemented, and with a series of git blame -L <line number> and git checkout <hash>^ (it should be able to automate this) I saw that at this commit: 
`460defb0 (Michael Huth 2017-03-13 16:43:38 +0100 837)`
the function EvaluateRTE was already implemented (possibly even long before).

So right now I am confused why the issue was opened in 2019.

**Comment by MathiasAugstein** [comment]
This function is already implemented with a try-catch-endtry and the function EvaluateRTE inside the testcase loop in RunTest.

The problem in the example is
> print getrTError(1)
which resets the RTE flag. As far as I understand, as long as we do not write the error value inside a global variable, the information that an RTE occurred is lost.

**Comment by t-b** [comment]
@MathiasAugstein So if you change `getRTError(1)` -> `getRTError(0)` in my example does the test case pass?

**Comment by MathiasAugstein** [comment]
Yes, but nevertheless Michael found a problem that a RTE error remains unrecognized if the abort-flag is set. So that problem is found thanks to this issue, and will be changed tomorrow.

And this is a good opportunity to expand Example8 in the manual.

**Comment by t-b** [comment]
Thx, I'll wait for the PR then.

**Comment by MichaelHuth** [comment]
Yes if one does a
```
WAVE w = $""
REQUIRE(0)

```it aborts due to the abort from require, but the lingering RTE is unreported.
This will be fixed by Mathias.

**Comment by t-b** [comment]
@MichaelHuth And

```
Function Dostuff()

	WAVE wv = $""
	print wv[0]
End
```

will be a failing test case? Just asking that we scope out the issue correctly ;)

**Comment by MichaelHuth** [comment]
This is failing with uncaught runtime error already in current master.

**Comment by t-b** [comment]
Got it.

**Comment by MathiasAugstein** [comment]
While trying to set up an additional test case for example8, I found that the abort flag (as set in REQUIRE(0) or FAIL() ) aborts the whole test suite. Is this a desired behavior or does it need to be changed?
If this is desired, then the explanation of example3 needs to be changed.
