### ISSUE TITLE
Use a good default execution order of test cases

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#109]
It seems that the order of test case execution is currently not easy to understand. I expect by default to execute the test cases from the top of the file to the bottom of the file and the test suites to run in the given order.

**Comment by ukos-git** [comment]
The execution order is mixed after combining multi-data tests and normal tests.

I have added a suggestion in https://github.com/byte-physics/igor-unit-testing-framework/pull/110
