### ISSUE TITLE
Multi data test cases should not require the generator function in the same procedure file

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#111]
It should rather search the whole independent module/ProcGlobal.

**Comment by ukos-git** [comment]
Isn't that a violation of test case isolation or do you consider the generator functions as never-failing helper functions?

**Comment by t-b** [comment]
@ukos-git Good point. I need to think about that.

**Comment by t-b** [comment]
The multi data test case generators should follow the same logic as the hook functions. And these work on a ProcGlobal/IM level and not on file level. See https://docs.byte-physics.de/igor-unit-testing-framework/examples.html#example5. Does that make sense?
