### ISSUE TITLE
multi data test case: Allow more function signatures with wave arguments

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#112]
The following test case

```igorpro
Function/WAVE Gen()

	Make/FREE/WAVE wv
	return wv
End

// UTF_TD_GENERATOR Gen
Function TestCase([WAVE/WAVE wv])
End
```

is not considered a valid test case as its function signature does not match one of the existing ones in https://github.com/byte-physics/igor-unit-testing-framework/blob/e1f316036131e13a9634c2a2ba5c37479f42b622/procedures/unit-testing-basics.ipf#L1177-L1220.

This requires users to work around by creating another wave reference. It would be nice to support these signatures out of the box.

**Comment by MichaelHuth** [comment]
There is already a generic wave type function template implemented and the correct code would be:

```
Function/WAVE Gen()

	Make/FREE/WAVE wv
	return wv
End

// UTF_TD_GENERATOR Gen
Function TestCase([WAVE wv])

	WAVE/WAVE w = wv
End

```

Do you think we should extend that to support directly typed waves as function parameter?
like:
WAVE/T
WAVE/DF
WAVE/WAVE
?
