### ISSUE TITLE
CHECK_EQUAL_WAVES does not detect difference between free and regular waves.

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#114]
Consider the following test function:

```
Function test()

	Make/T w1 = {"test"}
	Make/FREE/T w2 = {"test"}
	CHECK_EQUAL_WAVES(w1, w2)

End
```

This test runs through without error, but there should be an error like
`Assuming equality using mode <new mode here> for waves w1 and _free_: is false  Assertion "CHECK_EQUAL_WAVES(w1, w2)" failed in line ...`

**Comment by t-b** [comment]
Conclusion: Mention in documentation that the free/normal property of the wave is not checked. Use `*_WAVE` for that.
