### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#16]
- [ ] add a prominent link to the repository
- [ ] add a prominent link to https://www.byte-physics.de
- [ ] add info about the git commit which it was built from. MIES has something like that already.
- [ ] integrate with piwik and sphinx, see https://developer.matomo.org/guides/tracking-javascript-guide and https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html

**Comment by ukos-git** [comment]
https://github.com/byte-physics/igor-unit-testing-framework/pull/22

still missing the commit number. Functions are already there. Not sure, if it should be in the footer ?
