### ISSUE TITLE
CHECK_EQUAL_VAR(<null>, NaN) passes

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#18]
Using a NVAR reference which is `<null>`, when comparing with `CHECK_EQUAL_VAR(ref, NaN)` it passes.
I would expect the check to fail.

The problem is that a `<null>` NVAR gets implicitly converted to NaN when passed by value into CHECK_EQUAL_VAR and thus it compares equal. 

Also `variable num = invalid_ref` results in num = NaN and Igor does not throw an error.

If one does the same for strings Igor throws an error with 'attempt to use a <null> string'.

**Comment by t-b** [comment]
@MichaelHuth 

Thanks for the report. I was not aware of that issue. Any ideas for how we could fix/work around that? The implicit-conversion-to-nan sounds like an Igor issue to me.

Does it also fail with `rtFunctionErrors=1`?

 As in

```igorpro
#pragma rtGlobals=3
#pragma rtFunctionErrors=1

Function Test()

    NVAR/Z I_DONT_EXIST

    CHECK_EQUAL_VAR(0, I_DONT_EXIST)
End
```

I would guess that the reason why `*_EQUAL_STR` fails is that these functions take the string argument by reference and you can not pass a SVAR as string reference.

**Comment by MichaelHuth** [comment]
It is an Igor issue.

Also with `#pragma rtFunctionErrors=1`  Igor does not generate an error and the conversion to NaN takes place silently when the CHECK_EQUAL_VAR function is called.

The only thing we can do, if there is a chance that the reference is not valid, to check it for validity before CHECK_EQUAL_VAR is called when building the test cases:

```
    NVAR/Z I_DONT_EXIST
    
    CHECK(NVAR_Exists(I_DONT_EXIST))
    CHECK_EQUAL_VAR(NaN, I_DONT_EXIST)

```

With strings it is already different for simple assignments:

```
NVAR/Z I_DONT_EXIST
variable v = I_DONT_EXIST
SVAR/Z STR_DONT_EXIST
string s = STR_DONT_EXIST
```
only the fourth line generates an error.

I tested it in IP7 and IP8.

**Comment by t-b** [comment]
@MichaelHuth Thanks!

**Comment by t-b** [comment]
With the latest IP8 nightly from today you get a RTE if a NVAR could not be resolved.

So the example given here still fails, but one can do

```
#pragma rtGlobals=3
#pragma rtFunctionErrors=1
#include "unit-testing"

Function Test()

    NVAR I_DONT_EXIST

End
```

which gives

```
•runtest("procedure")
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Test"
  Uncaught runtime error 749:"NVAR;NVAR reference to "I_DONT_EXIST" failed." in test case "Test", procedure file "Procedure"
  The test case "Test" did not make any assertions!
  Leaving test case "Test"
  Failed with 1 errors
  Leaving test suite "Procedure"
  Test finished with 1 errors
  End of test "Unnamed"
```

and that fixes the issue I think. Please reopen if you don't agree.
