### ISSUE TITLE
Building documentation fails with msys/win

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#19]
The error message is:

`checking container:
c:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"C:/MinGW/msys/1.0/bin/bash\": stat C:/MinGW/msys/1.0/bin/bash: no such file or directory": unknown.`

There is no bash subfolder in bin on msys, so I created one and tried again. However it results in the same error, so I think the call requires backslash as separators in windows as well.

**Comment by t-b** [comment]
What did you execute?

Which make executable did you use? The one from common-orga-and-tools?

**Comment by MichaelHuth** [comment]
I started up msys from mingw and executed 'make' in the /docu subfolder.
It used the default make executable from msys.

**Comment by t-b** [comment]
@MichaelHuth make from msys probably  just does not work. A normal cmd prompt and minw32-make.exe from common-tools-and-orga should do the trick or?

**Comment by MichaelHuth** [comment]
I tried with mingw32-make.exe from common-tools-and-orga, when running from a regular command prompt in the docu subfolder I get:

```
process_begin: CreateProcess(NULL, make -C docker/debian, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
Makefile:24: recipe for target 'debian' failed
mingw32-make: *** [debian] Error 2
```

I also tried to run mingw32-make.exe from a msys prompt, which gives the same error as in the first comment.
