### ISSUE TITLE
Output summary at the end of test run

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#193]
When you run multiple test suites with a lot of tests, you sometimes have one test failure only. But finding that can take a lot of time as it requires diving through 5k lines of history output.

It would be nice to have a summary at the end of the test run. This should allow to quickly jump to any failed test.

**Comment by t-b** [comment]
- Gather test suite name and test case name in IncError(), save info in a global wave
- Output summary in Test End hook

**Comment by Garados007** [comment]
What do you think about the following output?

```
  Leaving test suite "Proc0"
  Test finished with 2 errors
    in Assertion "CHECK_EQUAL_VAR(a, b)" failed in line 25, procedure "Proc0"
    in Assertion "CHECK_EQUAL_VAR(a, b)" failed in line 32, procedure "Proc0"
  End of test "Unnamed"
```

**Comment by t-b** [comment]
@Garados007 Suppose one has multiple test suites where in each of them a test case fails. How can I see in your above example which test case failed in which test suite? I don't think the module name is important for the test case.

**Comment by Garados007** [comment]
At the moment I am not doing much fancy magic behind the scene. The first part (`Assertion "CHECK_EQUAL_VAR(a, b)" failed in line 25, procedure "Proc0"`) is just a part of the output for every assertion. This contains, the assertion method, the line number and the procedure file. The second part `function mymodule#FailedTest` is the name of the test case which consists of the module and method name.

The output might be misleading but its the same output that will be printed for every assertion if they occur. I just reuse it and keep it for the end of the test run.

I can also reorganize the information like so if you want:
```
Assertion "CHECK_EQUAL_VAR(a, b)" failed in mymodule#FailedTest (Proc0.ipf, line 25)
```
