### ISSUE TITLE
Investigate free wave leak tracking

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#200]
- IP9 only
- Add optional parameter to RunTest, defaulting to 0 for IP9, when set for IP<9 then error
- Use `WaveTracking`
- Wave leaks are a CHECK error
- Add to Test Case Begin / End use incrError() on fail
- add new function tag to disable this check for a specific test case (when parameter was 1)

**Comment by Garados007** [comment]
@t-b Can you provide a small testcase which always produce a wave leak?

**Comment by t-b** [comment]
@Garados007 https://github.com/byte-physics/igor-pro-coding-conventions/blob/423c938b57934d5f179ea0c30979598c3273b635/coding_conventions.tex#L656

**Comment by t-b** [comment]
I'm also currently in the process of getting that to rst, see https://github.com/byte-physics/igor-pro-coding-conventions/pull/23.
