### ISSUE TITLE
AreVariablesClose does not check properly if values are zero

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#216]
We calculate d1 and d2 in AreVariablesClose through division:
https://github.com/byte-physics/igor-unit-testing-framework/blob/989148e15e06e001a1d407465f9e148425f01f0d/procedures/unit-testing-assertion-checks.ipf#L127

If the variable to check is zero then d1 and/or d2 is NaN.
Thus, the following if check for strong fails if one is Nan and for weak it fails if both are NaN.

**Comment by t-b** [comment]
CLOSE_VAR_WRAPPER has the literature links. In short this algorithm has a known singularity at zero. Boost Test has some online documentation, see https://www.boost.org/doc/libs/1_77_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point/floating_points_comparison_theory.html.

This might need more mentioning in the documentation.

**Comment by t-b** [comment]
The algorithm is originally from "The art of computer programming (Vol II). Donald. E. Knuth. 0-201-89684-2. Addison-Wesley Professional; 3 edition, page 234 equation (34) and (35)".

**Comment by MichaelHuth** [comment]
Ok.

How about we add some notification output if the algorithm is called with zero values?
Or we catch that with an own assert message because it puts invalid input to the algorithm?

Despite the correctness of the algorithm, the result with 0 is at first glimpse unexpected and leaves questions to the IUTF user.

**Comment by Garados007** [comment]
I have read the [Boost Documentation Link](https://www.boost.org/doc/libs/1_77_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point/floating_points_comparison_theory.html) above. The following is written there:

> The above however, will not work when v or u is zero. In such cases the solution is to resort to a different algorithm, e.g. [(1)](https://www.boost.org/doc/libs/1_77_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point/floating_points_comparison_theory.html#equ1).

And the provided formula:

```cpp
abs(u - v) <= epsilon; // (1)
```

If I have to check for one of both sides to be zero to report the custom fail message, why not using formula (1) instead in this case? After this we have no singularity issues and the user doesn't have to be careful and can provide any (real) number.
