### ISSUE TITLE
Think about adding a way to add more output on assertion failures

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#233]
See [1] for how boost test does it or [2] for gtest.

[1]: https://www.boost.org/doc/libs/1_78_0/libs/test/doc/html/boost_test/test_output/test_tools_support_for_logging/contexts.html
[2]: https://google.github.io/googletest/advanced.html#adding-traces-to-assertions

**Comment by t-b** [comment]
Add following function:

```
TEST_INFO("Loop iteration: %d, other stuff %s", n0 = i, s0 = "abcd")
```

with 1 numeric plus 1 string arguments -> 4 combinations
- just string "as is"
- num
- string
- num + string

- Always evaluate so that the format string is validated
- Add with CR into a global string
- Output on next failed assertion
- Clear on next assertion
- Output on uncaught RTE
- Output on Abort/AbortOnValue
- Clear on test case end
- Add to systemErr in JUNIT
- Documentation/Tests

**Comment by t-b** [comment]
1. Fine with me.
2. Would the other approach support the full spectra of % varieties (precision, width, %x, etc.)? If yes, I'm okay with it. 5 variable plus 5 string parameters should be fine.
3. I don't think this is needed.

**Comment by Garados007** [comment]
@MichaelHuth and I discussed this issue over phone. We have come to the following conclusion:

1. Doing separate printf statements for each combination is not useful. You have 5 combinations of printf if you count the number of parameter and the order inside the format string. Adding more parameter in the future make it worse.
2. `ReplaceString` is not useful if we want to support the full spectra of % varieties. Regular expressions are better suited for this.
3. We have to support the replacement of `%%` to `%`.

This would be our solution for now:

1. Splitting the format string using `SplitString` in three parts: Before pattern, pattern, after pattern. We use `%[^a-zA-Z]*([feEgGdousxXbc]|W\dP)` as the pattern which matches **all** % varieties (and more).
2. Before pattern doesn't contain anything known for us to replace. This will be piped to `printf` to replace `%%` and catch unknown errors.
3. The pattern will be checked if `%s`. If so we do printf with one string parameter. If not with a numeric parameter.
4. Repeat Step 1 with the after pattern.
5. Combine all resulting parts and get the new string.

With this it is easy support 5 parameters and we can extend it in the future without any problems. We can also support waves as parameter with an unlimited number of arguments.

**Comment by t-b** [comment]
```igorpro
	Make/FREE/N=5 wv = p
	INFO("%s: @%d", s0 = "abcd", n = wv)
	// abcd: {0, 1, 2, 3, 4}
```
