### ISSUE TITLE
RunTest: execute test suites in given order

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#252]
If you currently run the MIES hardware tests it starts with:

```
 Start of test "MIES with Hardware"
  Entering test suite "UTF_AutoTestpulse.ipf"
  Entering test case "AutoTP#AutoTP_OptimumValues:NI"
...
```

although the given proc list started with "UTF_VeryBasicHardwareTests.ipf", see https://github.com/AllenInstitute/MIES/blob/cc03c651a29270697cac8a6c571d62259d3a29e4/Packages/Testing-MIES/UTF_HardwareMain.ipf#L94.

I expect that the testsuites are executed in the given order. Looking into `FindProcedures` sounds like a worthwhile starting point.

**Comment by MichaelHuth** [comment]
closed with https://github.com/AllenInstitute/MIES/pull/1414
