### ISSUE TITLE
CHECK_EQUAL_WAVES ignores mode for zero sized waves

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#254]
Example:

```
Function Test()
  Make/FREE/N=0 w1
  Make/FREE/D/N=0 w2
  CHECK_EQUAL_WAVES(w1, w2, mode = WAVE_DATA | DIMENSION_SIZES)
End

```

Assertion fails because the wave type is different, but the wave type should not be considered according to the mode setting.

**Comment by t-b** [comment]
We've reported that to WM already. And this is marked as wontfix. I'd be happy to add a workaround for this exact case.
