### ISSUE TITLE
Tracing: Z_ function should call WARN(0)/FAIL() on error from TUFXOP_GetStorage

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#260]
@MichaelHuth What do you think? That would have made finding the bug much easier.

**Comment by MichaelHuth** [comment]
We can add an internal error check there, but I think an ASSERT_TS would be more correct.

**Comment by t-b** [comment]
We don't have ASSERT_TS, this is a MIES function. But we can come up with something similiar and combine abortNow with printFailInfo.

**Comment by MichaelHuth** [comment]
Ok. Though, I think it would make sense to not use the IUTF assertions like FAIL() for errors than originate from within the IUTF itself.

**Comment by t-b** [comment]
Add something like BUG_TS/TSDS_ReadVar/TSDS_Write from MIES and use it.

**Comment by Garados007** [comment]
Aborting is difficult. `Z_` is marked as threadsafe and cannot contain any `abort` in it.
