### ISSUE TITLE
Test case hooks are evaluated as MD test cases in Igor Pro 6

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#266]
A test case hook like:

```
static Function TEST_SUITE_END_OVERRIDE(name)
	string name

End

```

created a valid FUNCREF with the MD test case prototype function
```
Function TEST_CASE_PROTO_MD_STR([str])
	string str

```

in Igor Pro 6. Thus, the hook is evaluated as potential MD test case.

Usually the test run is aborted because no data generator was specified for it.

**Comment by t-b** [comment]
Good observation. We could use FunctionInfo to query if the parameter is optional or not.
