### ISSUE TITLE
Think about adding basic code style CI

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#280]
In MIES we have https://github.com/AllenInstitute/MIES/blob/main/tools/check-code.sh which checks for common issues with code and some IP code checks.

We could leverage something like this here as well to avoid common PR reponses (No space after if, etc.).

One could also use a more structured approach via e.g. https://github.com/pre-commit/pre-commit. Thoughts?

**Comment by Garados007** [comment]
I support this idea but I would prefer the pipeline approach in the first place and maybe add the second one later.

**Comment by t-b** [comment]
@Garados007 What is the "second one"?

**Comment by Garados007** [comment]
The second one is your approach with https://github.com/pre-commit/pre-commit.
