### ISSUE TITLE
Should UTF_EXPECTED_FAILURE require the test to fail?

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#289]
```
#include "unit-testing"

// UTF_EXPECTED_FAILURE
Function Test()

	PASS()
End
```

Generates 

```
•runtest("Procedure")
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Test"
  Leaving test case "Test"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

which I find a bit suprising. Should we require that an expected failure test fails?

**Comment by Garados007** [comment]
Yes. I also think it's not intuitive that a test case which is **expected** to throw some kind of asserts succeeds if it finished without any assert.

**Comment by t-b** [comment]
> Yes. I also think it's not intuitive that a test case which is expected to throw some kind of asserts succeeds if it finished without any assert.

I'm not sure this is the exact problem I was thinking about.

The original rationale for `PASS()` was for cases like

```
static Function SomeTest()
   try
      Wave abcd = $"I_DONT_EXIST"; AbortOnRTE
      FAIL()
   catch
      PASS()
   endtry
End
```

where you don't want to check anything but also want to make sure that you had at least one assertion.

My original example can be also rewritten without `PASS()` as 

```igorpro
#include "unit-testing"

// UTF_EXPECTED_FAILURE
Function Test()

	CHECK(1)
End
```

which gives

```
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Test"
  Leaving test case "Test"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

Am I right that you also think that this test should not pass?

**Comment by Garados007** [comment]
Thanks for the explanation. I think your test case should not pass. If you combine `UTF_EXPECTED_FAILURE` and some kind of `PASS()` you get a test case that will always pass and never fail - and that's useless. Therefore `UTF_EXPECTED_FAILURE` should always require a **failed** assertion (and not any assertion).

**Comment by t-b** [comment]
> I think your test case should not pass.

Good! So we agree that it is currently buggy.
