### ISSUE TITLE
Make the default for string matching case-sensitive.

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#291]
For waves comparison the string matching is always case-sensitive and byte-wise for Igor >= 7.05. For CHECK_EQUAL_STR the default for string matching is case-insensitive which is not intuitive.

In my opinion we should change it to case-sensitive (with the option for case-insensitive matching) for all string checks because in a test case we are expecting exact data and we are not working with user input.

**Comment by t-b** [comment]
@Garados007 Can you provide a small example so that we see the problem? Having some code to look at always helps :)

**Comment by Garados007** [comment]
The `TestCaseSensitivityString` is working without any problem which is unexpected because I want to check if the generated output is correct. On the other hand `TestCaseSensitivityWave` returns the expected error because both waves contain different data.

```igorpro
static Function TestCaseSensitivityString()
	string outputOfFunc = "AbC"
	string expect = "abc"
	
	CHECK_EQUAL_STR(expect, outputOfFunc)
End

static Function TestCaseSensitivityWave()
	Make/FREE=1/T outputOfFunc = { "AbC" }
	Make/FREE=1/T expect = { "abc" }
	
	CHECK_EQUAL_WAVES(expect, outputOfFunc)
End
```
```
  Entering test case "mymodule#TestCaseSensitivityString"
  Leaving test case "mymodule#TestCaseSensitivityString"
  Entering test case "mymodule#TestCaseSensitivityWave"
  Assuming equality using mode WAVE_DATA for waves expect (0x085cfe4d60) and outputOfFunc (0x085cfe4d40); detailed: Text waves difference:
Wave1: expect (0x085cfe4d60)
Wave2: outputOfFunc (0x085cfe4d40)
Dimensions|Labels|Text        |
----------|------|------------|
[0]       |      |0:0:0> a b c|
          |      |0:0:0> A b C|
: is false. Assertion "CHECK_EQUAL_WAVES(expect, outputOfFunc)" failed in line 22, procedure "Proc0"
  Leaving test case "mymodule#TestCaseSensitivityWave"
```
