### ISSUE TITLE
CHECK_WAVE: Does not check inputs

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#296]
The following 

```igorpro
Function Fails()

	Make/FREE/D wv
	CHECK_WAVE(wv, 0, minorType = 0)
End
```

gives

```
•runtest("Procedure")
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "Fails"
  Leaving test case "Fails"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

Two problems:
- The input for majorType is not valid, but accepted
- The minor type is actually valid as this is NON_NUMERIC_WAVE (aka 0) but the test should fail with this interpretation

**Comment by Garados007** [comment]
In PR #288 the constant `NON_NUMERIC_WAVE` is changed to `0x100` to enable intentional selection of this property. This also results in 0 as an invalid minor type.
