### ISSUE TITLE
Fixing trailing whitespaces

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#299]
In PR #273 @t-b asked me to remove any trailing whitespaces in my code. I have done this by configuring my editor to do this automatically. But since then my editor is fixing **all** trailing whitespaces in all code files. This is kind of annoying. I have to manually check what have been changed by me to keep my commit clean.

**Comment by t-b** [comment]
@Garados007 Just make one PR with a commit which removes trailing whitespace. Then we are done. Our future code-style CI should then also flag any new whitespace errors.
