### ISSUE TITLE
Reorganize data storage of UTF test state

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#316]
Currently JUNIT/TAP output is generated on the fly via calls in `ExecuteHooks`. This has the disadvantage that this is difficult to test.

- Introduce a global state wave like TestRunSetup but instead for the setup this is done for the output
- Store all test state/output in that wave this should also replace most of the globals like assertionCounter, errorCounter
- Serialize this wave to JUNIT/TAP in the end
- Write tests for the global state wave

**Comment by t-b** [comment]
@Garados007 What do you think about moving this issue to the 1.10 milestone so that we have a longer period for stabilisation?

**Comment by Garados007** [comment]
I agree. The PR 327 needs a bit of more work.
