### ISSUE TITLE
Bug: Cannot set function tag "#TAPDescription"

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#328]
If I use the following code:

```igorpro
// #TAPDescription: Checking if '*' is the Answer to the Ultimate Question of Life, the Universe, and Everything
static Function TAPCheckNumber_not_nan()

	CheckNumber(char2num("*"))
End
```

*Source: https://github.com/byte-physics/igor-unit-testing-framework/blob/main/internal_dev/IM_tap_example1a-uncaught-aborts.ipf#L26-L30*

I get the following error:

```
error: A dimension label can't contain any of the following: single-quote, double-quote, semicolon, colon, or any control characters.
```

This happens because [`GetFunctionTagWave()`](https://github.com/byte-physics/igor-unit-testing-framework/blob/main/procedures/unit-testing-utils.ipf#L182) is trying to define a dimension label with the name `#TAPDescription:`.

Similar is with the function tag `#TAPDirective:`.

**Comment by t-b** [comment]
That does still work with IP8 and below. IP9 now requires dimension labels to be object names, not checking that in earlier versions was a bug.

Maybe we should strip away `#`/`:` when storing and looking it up as dimension label? Other solution would be store them in a text wave.
