### ISSUE TITLE
*_WAVE passes with NULL_WAVE and existing wave

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#33]
```
Function MyTest()

	Make/FREE wv
	REQUIRE_WAVE(wv, NULL_WAVE)

End
```

```
•runtest("Procedure", allowDebug=1)
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "MyTest"
  Leaving test case "MyTest"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

@ukos-git 
Am I using that wrong?

**Comment by ukos-git** [comment]
You are using it correctly. That is definitely a bug. The function was mostly built to check for the other types and `NULL_WAVE` is a very specific case that could also be handled by `WaveExists()`.

Unfortunately any input to the following function will Always be true as the statement in the first bracket will collapse to 0 in any case:

```igor
Function CheckType(type)
	Variable type

	return (type & NULL_WAVE) == NULL_WAVE
End
```

```console
•print CheckType(NULL_WAVE)
  1
•print CheckType(100)
  1
•print CheckType(pi)
  1
```

This also means that  any binary combination of `NULL_WAVE` will remove the `NULL_WAVE` in favor of the other flags, work which is probably what we want:

```igor
•print NULL_WAVE | FREE_WAVE | NUMERIC_WAVE
  33
•print FREE_WAVE | NUMERIC_WAVE
  33
```

I will add a PR.
