### ISSUE TITLE
Call TEST_SUITE_END_CONST when no test suite was ever created

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#347]
During checking #53 I found this bug.

If I abort in TEST_BEGIN user hook the `ExecuteHook` for `TEST_SUITE_END_CONST` is called which is not allowed as no `TEST_SUITE_BEGIN_CONST` was ever called before.

```
•run()
  Start of test "Unnamed"
  Encountered "Abort" in user hook "TEST_BEGIN_OVERRIDE" (No source procedure)
  Fatal: Error: Prototype function USER_HOOK_PROTO was called.
  Encountered "Abort" in user hook "" (aborting-user-hooks.ipf)
  Failed with  errors
  Leaving test suite ""
  Encountered "Abort" in user hook "TEST_END_OVERRIDE" (No source procedure)
  Test finished with 4 errors
    ▶ Encountered "Abort" in user hook "TEST_BEGIN_OVERRIDE" (No source procedure)
    ▶ Encountered "Abort" in user hook "" (aborting-user-hooks.ipf)
    ▶ Encountered "Abort" in user hook "TEST_END_OVERRIDE" (No source procedure)
  End of test "TEST_END_OVERRIDE"
```

1. `ExecuteHook` is called for `TEST_BEGIN_CONST`
2. User hook create an error
3. `ExecuteHook` is called for `TEST_SUITE_END_CONST` !!!
4. `ExecuteHook` is called for `TEST_END_CONST`

_Originally posted by @Garados007 in https://github.com/byte-physics/igor-unit-testing-framework/issues/53#issuecomment-1352736598_

**Comment by t-b** [comment]
Nice find!
