### ISSUE TITLE
Test assertion in data generators

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#353]
Found while playing around with #327:

```igorpro
#include "unit-testing"

Function/WAVE Gen()

	CHECK(0)
	
	Make/FREE/N=1 wv
	return wv
End

/// UTF_TD_GENERATOR Gen
Function MyTest([variable var])

	PASS()
End
```

gives

```
•runtest("procedure")
  0: is false. Assertion "CHECK(0)" failed in Gen (Procedure, line 8)
  Start of test "Unnamed"
  Entering test suite "Procedure"
  Entering test case "MyTest:0"
  Leaving test case "MyTest:0"
  Finished with no errors
  Leaving test suite "Procedure"
  Test finished with no errors
  End of test "Unnamed"
```

which is unexpected as the failed assertion is not taken into account into the end result. Now knowing the UTF code a bit this is not too suprising. And I actually think it is nice to be able to use assertions in data generators. Or what do you think?

Same result in main, f69bf5d1 (Merge pull request #352 from byte-physics/bugfix/wave-pointer-printing, 2022-12-20), or mb/refactor/316-data-storage 7f659630 (Docs: Add developer section, 2022-12-13).

Ways to solve that:
- [ ] Disallow assertions in inopportune times, like data generators, hook into EvaluateResults maybe
- [ ] Treat each data generator as testcase, and group those into a pre-setup suite. Don't enforce assertions in data generators though. Don't start the test run at all if that pre-setup test suite has assertion errors. Needs to output proper JUNIT/TAP. These special test cases also ignore all test case hooks.
- [ ] Collect assertion failures in data generators and attribute them to the respective test cases. This is a 1:N mapping as multiple testcase can have the same generator.

**Comment by Garados007** [comment]
Some thoughts about this:

The first option is the easiest way. We need to track if the UTF is currently in testing mode and fail if an assertion is called when it's not expected (e.g. inside data generators, hooks, or even outside `RunTests`). If a data generator fails (RTE, assertions, ...) we can bail out the test run right away.

The second option is a bit tricky and involves more code. As far as I understand this we don't have to create the pre-setup suite in `TestRunData`. We only need one for the output (see #316). This means we have to inject the corresponding output functions when the normal test suite is prepared for execution and the data generators are called. But here are some questions:

- Do we want to have a pre-setup test case for each real test case or only for ones that have data generators?
- We will always have two test suites in the output for each real test suite. Is this desired for all cases (e.g. if the setup test suite is empty)?
- Do we want to prefix or suffix the name of the pre-setup test suite? Do we want to restrict the names of normal test suites to don't have this prefix or suffix?

The third option doesn't seem to be a solution for me.

**Comment by t-b** [comment]
We do solution 2 (fake test suites, fake test cases).

**Comment by Garados007** [comment]
This issue depends on PR #381 which contains some groundwork to solve this issue.

**Comment by Garados007** [comment]
There are some difficulties while adding the fake test suites and test cases to collect the errors. The function `GetGeneratorWave` call each data generator and caches the result for later executions. This seems to be a good position to start and end the fake test cases.

The problem here is, that `GetGeneratorWave` is called by `CheckDGenOutput` which is executed for each test case that has a data generator assigned. `CheckDGenOutput` also performs all checks and emits errors for each test case with an invalid data generator. This function can output the same errors for the same data generator multiple times when used for different test functions.

But this behavior is problematic as such as it is difficult to inject errors to the fake test cases long after they are executed.

I would change the logic of the checks in such a way that these checks are executed only **once** and for each data generator. These errors are no longer connected to the dependend test cases! Doing this I can implement the logic with the fake test without any problems.

@t-b @MichaelHuth What do you think about this?

**Comment by MichaelHuth** [comment]
Thomas and I talked about that.

At the moment when the test run setup is created the data generators are called and immediately checked against the test case signatures if the data generators wave properties fit.

The approach would be to split that tight coupling of get and check:
- In the test run setup creation only determine dgenlist without further checking
- Then run the test suite that calls the data generators as part of TCs and collect there the generator waves, no extra checking of the waves
- After the test suite finishes do the checks between the data generator waves and the test case signatures. Same logic as already now, abort if something is setup wrongly.  
(We don't check that again when the MD/MMD TC is called later)

Currently, when CheckDGenOutput is called it is not part of any test case, it is part of the test run setup. Thus, if the Abort is hit in ReportErrorAndAbort it is not caught and the execution stops for good. This also means it stops for the first failed condition and will not collect multiple errors.
Maybe it is confusing if the same function is used inside TCs and outside TCs?

If you need more input just ping me for a chat.

**Comment by Garados007** [comment]
I created a new diagram which helped me to understand the control flow and your suggestion. I will add this to the documentation later.

![setup](https://user-images.githubusercontent.com/12125053/213667806-94a7fba3-2c2a-48fe-b64e-818a192cce59.svg)

Thanks for your help. ;)

**Comment by t-b** [comment]
@Garados007 Nice diagram again! You do know that doxygen can also create caller/callee graphs?

**Comment by t-b** [comment]
It's kind of hilarious that the text goes out of the box considering how much they charge for the software.

**Comment by Garados007** [comment]
> You do know that doxygen can also create caller/callee graphs?

No. I didn't know doxygen has this ability at all. And if I haven't excepted that this will be supported for Igor Pro. I will have to take a look in it.

> It's kind of hilarious that the text goes out of the box considering how much they charge for the software.

Don't know which box. And I have resized all of them by hand (I forgot that there is a built-in function 😅).

**Comment by t-b** [comment]
>  And I have resized all of them by hand

Ah okay.

> No. I didn't know doxygen has this ability at all. And if I haven't excepted that this will be supported for Igor Pro. I will have to take a look in it.

Yes it is supported with IP thanks to https://github.com/byte-physics/doxygen-filter-ipf. The doxygen setting is called: `CALL_GRAPH`/`CALLER_GRAPH`.
