### ISSUE TITLE
CI Pipeline unable to run for main

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#379]
[The Pipeline](https://gitlab.byte-physics.de:4001/mirror/igor-unit-testing-framework/-/pipelines/7404) after last [pull request](https://github.com/byte-physics/igor-unit-testing-framework/pull/327) was unable to run and show the following error:

> **Unable to create pipeline**
>
> - deployment: one job can only need 50 others, but you have listed 54. See needs keyword documentation for more details

The interesting thing is that [the CI](https://gitlab.byte-physics.de:4001/mirror/igor-unit-testing-framework/-/pipelines/7402) run without any problems inside the PR and had only 40 jobs.

**Comment by Garados007** [comment]
The `deployment` step failed as it is requiring all other steps to be finished first. And these are indeed 54 jobs. A solution could be to create a dummy job for this situation that awaits the parallel matrix and does nothing with the results. `deployment` is then only waiting on one job and no longer for all of them.

**Comment by t-b** [comment]
I've changed the limit in our gitlab instance to 500 according to https://docs.gitlab.com/ee/administration/cicd.html#set-the-needs-job-limit. Can you check that it works now?

**Comment by Garados007** [comment]
The newest builds on main are working and the previous [failed validation](https://gitlab.byte-physics.de:4001/mirror/igor-unit-testing-framework/-/ci/editor?branch_name=main) is working again. So it's fixed.
