### ISSUE TITLE
automatic log file naming

### ISSUE THREAD

**Issue by ukos-git** [byte-physics/igor-unit-testing-framework#38]
I think it would be good to have the log files produced with a static name instead of a name with the date.

Three reasons:
* automatic processing of the log file is more convenient if I know the exact name. Otherwise The directory needs to be cleaned of *.log and the single *.log file is the output of the script.
* Keeping the log file open with a text editor would automatically gives the newly created output
* a tailing pointer would be possible for use i.e. in `tail -f`

If data overwrite is a problem, a log rotate would be a possible solution.

**Comment by t-b** [comment]
@ukos-git Your reasoning is valid for writing testcases. An easy (hacky?) solution would be to just add a parameter to `RunTest`.

**Comment by ukos-git** [comment]
Why is it needed to rename log files. From my (linux) point of view, I want to have them at a defined, exact location.

I already have a "hacky" workaround:
@ autorun-test-IP8-64bit.bat:4 @
```diff
 :foundIgor
 
 echo "" > %StateFile%
+del *.log
 for /F "tokens=*" %%f IN ('dir /b *.pxp') do (
   echo Running experiment %%f
   %IgorPath% /I "%%f"
 )
+move *.log output.log
 del %StateFile%
 
 :done
```

A clean solution to this could be to
- output from Igor to a fixed named log file
- rename the log file within the batch file. ([datetime functions in batch](https://stackoverflow.com/a/1194991/7809404) are a bit of a mess but should work.)

**Comment by t-b** [comment]
Your solution does not work if multiples PXP are present.

I'm okay with adding a string parameter `logfile` to RunTest which determines the log file. If not present the current naming scheme is used. This would also remove the restriction that the experiment has been saved if `logfile` is present. Thoughts?

**Comment by ukos-git** [comment]
> Your solution does not work if multiples PXP are present.

This can of course also get added to the for loop if needed, although, I did not want propose a generic solution that could be merged to the project with the above script. I just wanted to point out that I do not need another "hacky" solution.

>adding a string parameter logfile to RunTest

I like the suggestion of an optional logfile parameter. If this parameter also removes the limitaion of using the utf in unsaved experiments, this is also an improvement.

**Comment by t-b** [comment]
Conclusion:
- Add parameter to RunTest to use a fixed name for the logfile. This should also remove the limitation that have to save the experiment.
