### ISSUE TITLE
AfterTestCaseUserHook never executed if user hook failed with RTE or Abort

### ISSUE THREAD

**Issue by Garados007** [byte-physics/igor-unit-testing-framework#385]
Is this intended behavior? AfterTestCaseUserHook is responsible for the following things:

- cleanup work data folder
- reset data folder to last data folder
- wave tracking leak checks

**Comment by t-b** [comment]
> Is this intended behavior?.

IMHO no. I think the IUTF hooks should always be executed now matter what the user hooks do.

Do you agree?

**Comment by Garados007** [comment]
I don't know why the listed tasks shouldn't be executed if a user hook failed with an RTE or abort. So yes. They should always be executed.
