### ISSUE TITLE
Redesign EQUAL_WAVE_WRAPPER for identical wave references

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#49]
It is not connected to the DimLabel patch, but I find the following code failing unexpected:

```
	Make/N=0 w1
	WAVE w2=w1

	CHECK_EQUAL_WAVES(w1,w2)
```

_Originally posted by @MichaelHuth in https://github.com/byte-physics/igor-unit-testing-framework/pull/44#issuecomment-472812939_

**Comment by t-b** [comment]
Yes that needs to be changed.

**Comment by MathiasAugstein** [comment]
So the better solution would be to output nothing if two wave references point to the same wave? Sounds like we could need an additional assertion *EQUAL_WAVE_REFERENCES to check if both wave references are the same, so basically split *EQUAL_WAVES into two assertions.

**Comment by t-b** [comment]
@MathiasAugstein (Please mention me on direct questions.)

> So the better solution would be to output nothing if two wave references point to the same wave? 

Currently we fail with an error if both wave references are not identical. And that should not fail anymore.

@MichaelHuth Feel free to object here.

> Sounds like we could need an additional assertion *EQUAL_WAVE_REFERENCES to check if both wave references are the same, so basically split *EQUAL_WAVES into two assertions.

Yes we could do that in the future, please create a new issue for that.

**Comment by t-b** [comment]
Just remove the `!WaveRefsEqual` check from EQUAL_WAVE_WRAPPER and adapt tests and documentation.
