### ISSUE TITLE
TAP: Avoid errorring out with aborting user hooks

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#53]
Running `AbortingUserHooks.pxp` with `enableTAP=1` gives

![grafik](https://user-images.githubusercontent.com/1185677/54682721-fba50780-4b0f-11e9-8b01-182b80b16aa9.png)

**Comment by Garados007** [comment]
I have tried to reproduce this using the patches in PR #327 (HEAD: 7f65963 (Docs: Add developer section, 2022-12-13)). I enabled JU and TAP. Neither of them produce this error.

```
•run()
  Start of test "Unnamed"
  Encountered "Abort" in user hook "TEST_BEGIN_OVERRIDE" (No source procedure)
  Fatal: Error: Prototype function USER_HOOK_PROTO was called.
  Encountered "Abort" in user hook "" (aborting-user-hooks.ipf)
  Failed with  errors
  Leaving test suite ""
  Encountered "Abort" in user hook "TEST_END_OVERRIDE" (No source procedure)
  Test finished with 4 errors
    ▶ Encountered "Abort" in user hook "TEST_BEGIN_OVERRIDE" (No source procedure)
    ▶ Encountered "Abort" in user hook "" (aborting-user-hooks.ipf)
    ▶ Encountered "Abort" in user hook "TEST_END_OVERRIDE" (No source procedure)
  End of test "TEST_END_OVERRIDE"
```

But I found an interesting bug:
1. `ExecuteHook` is called for `TEST_BEGIN_CONST`
2. User hook create an error
3. `ExecuteHook` is called for `TEST_SUITE_END_CONST` !!!
4. `ExecuteHook` is called for `TEST_END_CONST`

The third step isn't allowed as no test suite was created!

**Comment by t-b** [comment]
Okay if it does not reproduce the internal storage rewrite in #327 did fix it. Nice!
