### ISSUE TITLE
ExecuteHooks/EvaluateRTE: Clarify usage of procWin

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-unit-testing-framework#56]
ExecuteHooks accepts a procWin parameter. It passes that to JU_ hooks.
In an error case it is also passed to EvaluateRTE. That function uses it for the error message which says that the hook originated from procWin. But this is incorrect as the hook can be defined in a totally different procedure.

Can we easily fix that? Or do we need procWin in EvaluateRTE really? If not it might be just easier to remove it from EvaluateRTE.

**Comment by Garados007** [comment]
I have checked for what `procWin` is used right now:

![procWin-in-ExecuteHooks](https://user-images.githubusercontent.com/12125053/214362476-d5c93a56-8f25-4d89-9114-346232bbc795.svg)

It seems like that `procWin` cannot be removed that easily if we want to keep the output messages the same. In my opinion, we can close this issue.
