### ISSUE TITLE
Better error message if static hook is defined without #ModuleName

### ISSUE THREAD

**Issue by MichaelHuth** [byte-physics/igor-unit-testing-framework#64]
Currently the UTF reports in this case:

The override test hook \"%s\" must accept exactly one string parameter.\r", StringByKey("NAME", info[i])

from AbortWithInvalidHook(...)

The problem is that AbortWithInvalidHooks tries to parse the error message from getFullFunctionName(...) that is put into the info array with FunctionInfo, resulting in an empty string.

The error message from getFullFunctionName(...) instead of the function name:
`			sprintf errMsg, "The procedure file %s is missing a \"#pragma ModuleName=myName\" declaration.\r", procName
`
should be caught in AbortWithInvalidHook() with a nicer error.

**Comment by t-b** [comment]
Thx. Feel free to tackle that.

**Comment by t-b** [comment]
Closed via #83.
